"""Shared pytest fixtures that prevent CI hangs when API keys are absent."""

import os
from unittest.mock import MagicMock, patch

import pytest


def pytest_configure(config):
    for marker in ("unit", "integration", "smoke"):
        config.addinivalue_line("markers", f"{marker}: {marker}-level tests")


_API_KEY_ENV_VARS = (
    "OPENAI_API_KEY",
    "GOOGLE_API_KEY",
    "ANTHROPIC_API_KEY",
    "XAI_API_KEY",
    "DEEPSEEK_API_KEY",
    "DASHSCOPE_API_KEY",
    "DASHSCOPE_CN_API_KEY",
    "ZHIPU_API_KEY",
    "ZHIPU_CN_API_KEY",
    "MINIMAX_API_KEY",
    "MINIMAX_CN_API_KEY",
    "OPENROUTER_API_KEY",
    "AZURE_OPENAI_API_KEY",
    "ALPHA_VANTAGE_API_KEY",
)

_TRADINGAGENTS_ENV_VARS = (
    "TRADINGAGENTS_ANALYSIS_SYMBOL",
    "TRADINGAGENTS_BROKER_SYMBOL",
    "TRADINGAGENTS_LLM_PROVIDER",
    "TRADINGAGENTS_DEEP_THINK_LLM",
    "TRADINGAGENTS_QUICK_THINK_LLM",
    "TRADINGAGENTS_LLM_BACKEND_URL",
    "TRADINGAGENTS_OUTPUT_LANGUAGE",
    "TRADINGAGENTS_CHECKPOINT_ENABLED",
    "TRADINGAGENTS_TIMEFRAME",
    "TRADINGAGENTS_CONFIRMATION_TIMEFRAME",
    "TRADINGAGENTS_MARKET_TIMEZONE",
    "TRADINGAGENTS_RUNNER_POLL_SECONDS",
    "TRADINGAGENTS_RUNNER_MAX_CYCLES",
    "TRADINGAGENTS_RUNNER_MAX_RUNTIME_SECONDS",
    "TRADINGAGENTS_RUNNER_MAX_SESSION_LOSS",
    "TRADINGAGENTS_RUNNER_LOSS_STREAK_COOLDOWN_COUNT",
    "TRADINGAGENTS_RUNNER_LOSS_STREAK_COOLDOWN_SECONDS",
    "TRADINGAGENTS_RUNNER_BLOCKED_STRATEGY_RULES",
    "TRADINGAGENTS_TIME_FILTER_MODE",
    "TRADINGAGENTS_DECISION_MODE",
    "TRADINGAGENTS_MIN_SETUP_GRADE",
    "TRADINGAGENTS_B_PLUS_MIN_RR",
    "TRADINGAGENTS_FAST_ENTRIES_ENABLED",
    "TRADINGAGENTS_FAST_TIMEFRAME",
    "TRADINGAGENTS_FAST_CONFIRMATION_TIMEFRAME",
    "TRADINGAGENTS_FAST_HISTORY_WINDOW_CANDLES",
    "TRADINGAGENTS_NORMAL_ACTIVATION_WINDOW_MINUTES",
    "TRADINGAGENTS_FAST_ACTIVATION_WINDOW_MINUTES",
    "TRADINGAGENTS_FAST_COUNTER_BIAS_MIN_GRADE",
    "TRADINGAGENTS_MIN_STOP_DISTANCE_PRICE",
    "TRADINGAGENTS_MIN_STOP_SPREAD_MULTIPLE",
    "TRADINGAGENTS_RESULTS_DIR",
    "TRADINGAGENTS_CACHE_DIR",
    "TRADINGAGENTS_MT5_LOGIN",
    "TRADINGAGENTS_MT5_PASSWORD",
    "TRADINGAGENTS_MT5_SERVER",
    "TRADINGAGENTS_MT5_SYMBOL",
    "TRADINGAGENTS_MT5_PATH",
    "TRADINGAGENTS_MT5_ALLOW_REAL_ORDERS",
    "TRADINGAGENTS_MT5_EXPECTED_LOGIN",
    "TRADINGAGENTS_MT5_EXPECTED_SERVER",
    "TRADINGAGENTS_MT5_VOLUME",
    "TRADINGAGENTS_MT5_DEVIATION",
    "TRADINGAGENTS_MT5_MAGIC",
    "TRADINGAGENTS_MT5_ORDER_COMMENT",
    "TRADINGAGENTS_MAX_ENTRY_DISTANCE_POINTS",
)


@pytest.fixture(autouse=True)
def _dummy_api_keys(monkeypatch):
    for env_var in _API_KEY_ENV_VARS:
        monkeypatch.setenv(env_var, os.environ.get(env_var, "placeholder"))


@pytest.fixture(autouse=True)
def _isolate_local_tradingagents_env(monkeypatch):
    for env_var in _TRADINGAGENTS_ENV_VARS:
        monkeypatch.setenv(env_var, "")


@pytest.fixture()
def mock_llm_client():
    client = MagicMock()
    client.get_llm.return_value = MagicMock()
    with patch(
        "tradingagents.llm_clients.factory.create_llm_client",
        return_value=client,
    ):
        yield client
